/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_cuidadoconelmichi;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LUISA
 */
public class Menu_Principal extends javax.swing.JFrame {
    
    Connection cn;

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }
Menu_Director panelAdministracion;
Menu_Cliente panelCliente;
Menu_Empleado panelEmpleado;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ADMIN_MENU = new javax.swing.JButton();
        EMPLEADO_MENU = new javax.swing.JButton();
        CLIENTE_MENU = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Conect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CUIDADO CON EL MICHI");

        ADMIN_MENU.setText("ADMINISTRACION");
        ADMIN_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMIN_MENUActionPerformed(evt);
            }
        });

        EMPLEADO_MENU.setText("PERSONAL");
        EMPLEADO_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPLEADO_MENUActionPerformed(evt);
            }
        });

        CLIENTE_MENU.setText("CLIENTES");
        CLIENTE_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIENTE_MENUActionPerformed(evt);
            }
        });

        Salir.setText("Salir");

        Conect.setText("Conectar");
        Conect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Conect)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ADMIN_MENU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EMPLEADO_MENU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CLIENTE_MENU))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADMIN_MENU)
                    .addComponent(EMPLEADO_MENU)
                    .addComponent(CLIENTE_MENU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(Conect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EMPLEADO_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPLEADO_MENUActionPerformed
        // TODO add your handling code here:
        panelEmpleado=new Menu_Empleado();
        panelEmpleado.setVisible(true);
        panelEmpleado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_EMPLEADO_MENUActionPerformed

    private void ADMIN_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMIN_MENUActionPerformed
        // TODO add your handling code here:
        panelAdministracion=new Menu_Director();
        panelAdministracion.setVisible(true);
        panelAdministracion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ADMIN_MENUActionPerformed

    private void CLIENTE_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIENTE_MENUActionPerformed
        // TODO add your handling code here:
        panelCliente=new Menu_Cliente();
        panelCliente.setVisible(true);
        panelCliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_CLIENTE_MENUActionPerformed

    private void ConectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectActionPerformed
        // TODO add your handling code here:
    Conexion con=new Conexion();
    cn = con.conectar();
    }//GEN-LAST:event_ConectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADMIN_MENU;
    private javax.swing.JButton CLIENTE_MENU;
    private javax.swing.JButton Conect;
    private javax.swing.JButton EMPLEADO_MENU;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
