/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_cuidadoconelmichi;

import java.sql.Connection;

/**
 *
 * @author LUISA
 */
public class Menu_Director extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Director
     */
    public Menu_Director() {
        initComponents();
    }
EMPLEADO panelEmpleado;
DIRECTOR panelDirector;
AREA panelArea;
PROVEEDOR panelProveedor;
TIENDA_DE_ROPA panelTienda;
PRENDA panelPrenda;
Menu_Principal panelPrincipal;

    Menu_Director(Connection cn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DIRECTOR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        AREA = new javax.swing.JButton();
        PROVEEDOR = new javax.swing.JButton();
        TIENDA_DE_ROPA = new javax.swing.JButton();
        EMPLEADO = new javax.swing.JButton();
        Consultas_Admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DIRECTOR.setText("DIRECTORES");
        DIRECTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIRECTORActionPerformed(evt);
            }
        });

        jLabel1.setText("ADMINISTRACION");

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        AREA.setText("AREA");
        AREA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREAActionPerformed(evt);
            }
        });

        PROVEEDOR.setText("PROVEEDOR");
        PROVEEDOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROVEEDORActionPerformed(evt);
            }
        });

        TIENDA_DE_ROPA.setText("TIENDA DE ROPA");
        TIENDA_DE_ROPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIENDA_DE_ROPAActionPerformed(evt);
            }
        });

        EMPLEADO.setText("EMPLEADO");
        EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPLEADOActionPerformed(evt);
            }
        });

        Consultas_Admin.setText("SUPERVISION");
        Consultas_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultas_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TIENDA_DE_ROPA)
                            .addComponent(PROVEEDOR)
                            .addComponent(AREA))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Atras))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DIRECTOR)
                                    .addComponent(Consultas_Admin)
                                    .addComponent(EMPLEADO))
                                .addGap(0, 105, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIRECTOR)
                    .addComponent(TIENDA_DE_ROPA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AREA)
                    .addComponent(EMPLEADO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultas_Admin)
                    .addComponent(PROVEEDOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Atras))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DIRECTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIRECTORActionPerformed
        panelDirector=new DIRECTOR();
        panelDirector.setVisible(true);
        panelDirector.setLocationRelativeTo(null);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_DIRECTORActionPerformed

    private void AREAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREAActionPerformed
        panelArea=new AREA();
        panelArea.setVisible(true);
        panelArea.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_AREAActionPerformed

    private void PROVEEDORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROVEEDORActionPerformed
        panelProveedor=new PROVEEDOR();
        panelProveedor.setVisible(true);
        panelProveedor.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_PROVEEDORActionPerformed

    private void TIENDA_DE_ROPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIENDA_DE_ROPAActionPerformed
        panelTienda=new TIENDA_DE_ROPA();
        panelTienda.setVisible(true);
        panelTienda.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TIENDA_DE_ROPAActionPerformed

    private void EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPLEADOActionPerformed
        panelEmpleado=new EMPLEADO();
        panelEmpleado.setVisible(true);
        panelEmpleado.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_EMPLEADOActionPerformed

    private void Consultas_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultas_AdminActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_Consultas_AdminActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        panelPrincipal=new Menu_Principal();
        panelPrincipal.setVisible(true);
        panelPrincipal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Director.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Director().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AREA;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Consultas_Admin;
    private javax.swing.JButton DIRECTOR;
    private javax.swing.JButton EMPLEADO;
    private javax.swing.JButton PROVEEDOR;
    private javax.swing.JButton TIENDA_DE_ROPA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
