CREATE DATABASE CUIDADO_CON_EL_MICHI_5;
USE CUIDADO_CON_EL_MICHI_5;
--	01
CREATE TABLE TIENDA_DE_ROPA
(
TIENDA VARCHAR(30) NOT NULL,
Estado VARCHAR(30) NOT NULL,
Municipio VARCHAR(30) NOT NULL,
Colonia VARCHAR(30) NOT NULL,
Calle VARCHAR(30) NOT NULL,
NumInt VARCHAR(30) NOT NULL,
NumExt VARCHAR(30) NOT NULL,
TELL VARCHAR(30) NOT NULL
PRIMARY KEY (TIENDA)
);

--	02
CREATE TABLE DIRECTOR
(
ID_Director CHAR(10) NOT NULL,
NomDirector VARCHAR(30) NOT NULL,
PRIMER_APELLIDO VARCHAR(30) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(30) NOT NULL,
EstadoD VARCHAR(30) NOT NULL,
MunicipioD VARCHAR(30) NOT NULL,
ColoniaD VARCHAR(30) NOT NULL,
CalleD VARCHAR(30) NOT NULL,
NumIntD VARCHAR(30) NOT NULL,
NumExtD VARCHAR(30) NOT NULL,
TELLD VARCHAR(30) NOT NULL,
TELLMovilD VARCHAR(30) NOT NULL,
NombreT VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_Director),
FOREIGN KEY (NombreT) REFERENCES TIENDA_DE_ROPA
);


--	03
CREATE TABLE AREA
(
ID_Area CHAR(10) NOT NULL,
Nombre_Area VARCHAR(30) NOT NULL,
TIENDA VARCHAR (30) NOT NULL,
PRIMARY KEY (ID_Area),
FOREIGN KEY (TIENDA) REFERENCES TIENDA_DE_ROPA
);
 
--	04
CREATE TABLE EMPLEADO 
(
ID_Empleado CHAR(10) NOT NULL,
ID_Area CHAR(10) NOT NULL,
NomEmpleado VARCHAR(30) NOT NULL,
PRIMER_APELLIDOE VARCHAR(30) NOT NULL,
SEGUNDO_APELLIDOE VARCHAR(30) NOT NULL,
EstadoE VARCHAR(30) NOT NULL,
MunicipioE VARCHAR(30) NOT NULL,
ColoniaE VARCHAR(30) NOT NULL,
CalleE VARCHAR(30) NOT NULL,
NumIntE VARCHAR(30) NOT NULL,
NumExtE VARCHAR(30) NOT NULL,
TELLE VARCHAR(30) NOT NULL,
TELLMovilE VARCHAR(30) NOT NULL,
TipoEmpleado VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_Empleado)
);

--	05
CREATE TABLE VENDEDOR 
(
ID_EMPLEADO CHAR(10) NOT NULL,
ID_Area CHAR(10) NOT NULL,
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO,
FOREIGN KEY (ID_Area) REFERENCES AREA
);

--	06
CREATE TABLE CAJERO 
(
ID_EMPLEADO CHAR(10) NOT NULL,
PRIMARY KEY (ID_EMPLEADO),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO
);

--	07
CREATE TABLE GERENTE
(
ID_EMPLEADO CHAR(10) NOT NULL,
PRIMARY KEY (ID_EMPLEADO),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO,
);

--	08
CREATE TABLE VIGILANTE
(
ID_EMPLEADO CHAR(10) NOT NULL,
TIENDA VARCHAR(30) NOT NULL,
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO,
FOREIGN KEY (TIENDA) REFERENCES TIENDA_DE_ROPA
);

--	09
CREATE TABLE PROVEEDOR
(
ID_PROVEEDOR CHAR (30) NOT NULL,
NomProveedor VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_PROVEEDOR)
);

--	10
CREATE TABLE COMPRA
(
ID_PRODUCTO CHAR(10) NOT NULL,
NUM_COMPRA INTEGER NOT NULL,
ID_PROVEEDOR CHAR(30) NOT NULL,
FECHA_COMPRA DATE  NOT NULL,
NUM_PIEZAS INTEGER NOT NULL,
COSTO_U FLOAT NOT NULL,
ID_Empleado CHAR(10) NOT NULL,
PRIMARY KEY (ID_PRODUCTO),
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR,
FOREIGN KEY (ID_Empleado) REFERENCES GERENTE	/*es el gerente*/
);
-------------------------------
-- 11
CREATE TABLE PRENDA
( 
ID_PRENDA CHAR(10) NOT NULL,
Area CHAR(10) Not NULL,
TALLA CHAR(5) NOT NULL,
MARCA VARCHAR(30) NOT NULL,
EXITENCIAS INTEGER NOT NULL,
TIPO_PRENDA VARCHAR(30) NOT NULL,
PRECIO INTEGER NOT NULL,
PRIMARY KEY (ID_PRENDA),
FOREIGN KEY (Area) References AREA,
FOREIGN KEY (ID_PRENDA) REFERENCES COMPRA,
);

--	12
CREATE TABLE VENTA
(
NUM_VENTA INTEGER NOT NULL,
FECHA_VENTA DATE NOT NULL,
ID_CAJERO CHAR(10) NOT NULL,
ARTICULO CHAR(10) NOT NULL,
PRIMARY KEY(NUM_VENTA),
FOREIGN KEY (ARTICULO) REFERENCES PRENDA,
FOREIGN KEY (ID_CAJERO) REFERENCES CAJERO	/*es el cajero*/
);

select*from VENTA;


--INSERTAR DATOS
INSERT INTO TIENDA_DE_ROPA(TIENDA,Estado,Municipio,Colonia,Calle,NumInt,NumExt,TELL)
	VALUES('Cuidadp con el Michi','MEXICO','ECATEPEC DE MORELOS','SAN PEDRO','5 DE FEBRERO','05','23','56101031');
------------------------------------
INSERT INTO DIRECTOR(ID_Director,NomDirector,PRIMER_APELLIDO,SEGUNDO_APELLIDO,EstadoD,MunicipioD,ColoniaD,CalleD,NumIntD,NumExtD,TELLD,TELLMovilD, NombreT)
	VALUES('D01','LUIS','LOPEZ','VIDAL','MEXICO','ECATEPEC DE MORELOS','PIEDRA GRANDE','JOSUE VALDEZ MONDRAGON','05','03','59601020','5610103180','Cuidadp con el Michi');
------------------------------------
INSERT INTO AREA(ID_Area,Nombre_Area,TIENDA)
	VALUES('G01','GENERAL','Cuidadp con el Michi');
----------------------------
INSERT INTO EMPLEADO(ID_Empleado,ID_Area,NomEmpleado,PRIMER_APELLIDOE,SEGUNDO_APELLIDOE,EstadoE,MunicipioE,ColoniaE,CalleE,NumExtE,NumIntE,TELLE,TELLMovilE,TipoEmpleado)
	VALUES('V01','G01','DIEGO','MARQUEZ','TELLEZ','MEXICO','ECATEPEC','CARACOLES','PIRULES','03','04','98761253','5515235542','VENDEDOR');

INSERT INTO EMPLEADO(ID_Empleado,ID_Area,NomEmpleado,PRIMER_APELLIDOE,SEGUNDO_APELLIDOE,EstadoE,MunicipioE,ColoniaE,CalleE,NumExtE,NumIntE,TELLE,TELLMovilE,TipoEmpleado)
	VALUES('C01','G01','KEVIN','MARQUEZ','LOPEZ','MEXICO','ECATEPEC','CARACOLES','PIRULES','03','04','98761253','5515235542','CAJERO');

INSERT INTO EMPLEADO(ID_Empleado,ID_Area,NomEmpleado,PRIMER_APELLIDOE,SEGUNDO_APELLIDOE,EstadoE,MunicipioE,ColoniaE,CalleE,NumExtE,NumIntE,TELLE,TELLMovilE,TipoEmpleado)
	VALUES('GE01','G01','MANUEL','RAMIREZ','TREJO','MEXICO','ECATEPEC','ARBOLITOS','CANARIAS','08','14','921630265','5512537864','GERENTE');

INSERT INTO EMPLEADO(ID_Empleado,ID_Area,NomEmpleado,PRIMER_APELLIDOE,SEGUNDO_APELLIDOE,EstadoE,MunicipioE,ColoniaE,CalleE,NumExtE,NumIntE,TELLE,TELLMovilE,TipoEmpleado)
	VALUES('VI01','G01','JOSE','RODRIGUEZ','SANTIAGO','MEXICO','ECATEPEC','JARDINES C.','GASEODUCTO AV.','10','07','38012995','5610366698','VIGILANTE');

----------------------------
INSERT INTO VENDEDOR(ID_EMPLEADO,ID_Area)
	VALUES('V01','G01');
----------------------------
INSERT INTO CAJERO(ID_EMPLEADO)
	VALUES('C01');
----------------------------
INSERT INTO GERENTE(ID_EMPLEADO)
	VALUES('GE01');
----------------------------
INSERT INTO VIGILANTE(ID_EMPLEADO,TIENDA)
	VALUES('VI01','Cuidadp con el Michi');
-------------------------------
INSERT INTO PROVEEDOR(ID_PROVEEDOR,NomProveedor)
	VALUES('P01','NIKE');
-------------------------------
INSERT INTO COMPRA(ID_PRODUCTO,NUM_COMPRA,ID_PROVEEDOR,FECHA_COMPRA,NUM_PIEZAS,COSTO_U,ID_Empleado)
	VALUES('NIKE001',1,'P01','03/06/2021',15,150.99,'GE01');
--------------------------------
INSERT INTO PRENDA(ID_PRENDA,Area,TALLA,MARCA,EXITENCIAS,TIPO_PRENDA,PRECIO)
	VALUES('NIKE001','G01',15,'NIKE',15,'CAMISETA',170.99);
--------------------------------
INSERT INTO VENTA(NUM_VENTA,FECHA_VENTA,ID_CAJERO,ARTICULO)
	VALUES(1,'03/06/2021','C01','NIKE001');

/* PRODUCTOS ALMACENADOS*/

-----01
--->AGREGAR
CREATE PROCEDURE AGREGAR_TIENDA_DE_ROPA(@P_TIENDA VARCHAR(30),
 @P_Estado VARCHAR(30),
 @P_Municipio VARCHAR(30),
 @P_Colonia VARCHAR(30),
 @P_Calle VARCHAR(30),
 @P_NumInt VARCHAR(30),
 @P_NumExt VARCHAR(30),
 @P_TELL VARCHAR(30)) AS 
INSERT INTO TIENDA_DE_ROPA(TIENDA, 
Estado,
Municipio,
Colonia,
Calle,
NumInt,
NumExt,
TELL)
VALUES (@P_TIENDA,
 @P_Estado,
 @P_Municipio,
 @P_Colonia,
 @P_Calle,
 @P_NumInt,
 @P_NumExt,
 @P_TELL);
GO
---->MODIFICAR
CREATE PROCEDURE MODIFICAR_TIENDA_DE_ROPA (@P_TIENDA VARCHAR(30),
 @P_Estado VARCHAR(30),
 @P_Municipio VARCHAR(30),
 @P_Colonia VARCHAR(30),
 @P_Calle VARCHAR(30),
 @P_NumInt VARCHAR(30),
 @P_NumExt VARCHAR(30),
 @P_TELL VARCHAR(30)) AS 
 UPDATE TIENDA_DE_ROPA
 SET TIENDA=@P_TIENDA, 
Estado=@P_Estado,
Municipio=@P_Municipio,
Colonia=@P_Colonia,
Calle=@P_Calle,
NumInt=@P_NumInt,
NumExt=@P_NumExt,
TELL=@P_TELL WHERE TIENDA=@P_TIENDA;
GO 
----->BORRAR
CREATE PROCEDURE BORRAR_TIENDA_DE_ROPA (@P_TIENDA VARCHAR(30)) AS
 IF EXISTS (SELECT *FROM TIENDA_DE_ROPA WHERE TIENDA=@P_TIENDA)
 BEGIN
 DELETE FROM TIENDA_DE_ROPA WHERE TIENDA=@P_TIENDA;
 END 

DROP PROCEDURE BORRAR_TIENDA_DE_ROPA
EXECUTE AGREGAR_TIENDA_DE_ROPA 'HOLAHOLA','CDMX','Iztacalco','Benito Juarez','Constitucion','200','304','5514526531';
EXECUTE MODIFICAR_TIENDA_DE_ROPA 'Nike','CDMX','HOLAHOLA','Benito Juarez','Constitucion','200','304','5514526531';
EXECUTE BORRAR_TIENDA_DE_ROPA 'HOLAHOLA';
SELECT*FROM TIENDA_DE_ROPA;

----02
--->AGREGAR
CREATE PROCEDURE AGREGAR_DIRECTOR(@P_ID_Director CHAR(10),
 @P_NomDirector VARCHAR(30),
 @P_PRIMER_APELLIDO VARCHAR(30),
 @P_SEGUNDO_APELLIDO VARCHAR(30),
 @P_EstadoD VARCHAR(30),
 @P_MunicipioD VARCHAR(30),
 @P_ColoniaD VARCHAR(30),
 @P_CalleD VARCHAR(30),
 @P_NumIntD VARCHAR(30),
 @P_NumExtD VARCHAR(30),
 @P_TELLD VARCHAR(30),
 @P_TELLMovilD VARCHAR(30),
 @P_NombreT VARCHAR(30)) AS 
INSERT INTO DIRECTOR(ID_Director, 
NomDirector, 
PRIMER_APELLIDO,
SEGUNDO_APELLIDO,
EstadoD,
MunicipioD,
ColoniaD,
CalleD,
NumIntD,
NumExtD,
TELLD,
TELLMovilD,
NombreT)
VALUES (@P_ID_Director,
 @P_NomDirector,
 @P_PRIMER_APELLIDO,
 @P_SEGUNDO_APELLIDO,
 @P_EstadoD,
 @P_MunicipioD,
 @P_ColoniaD,
 @P_CalleD,
 @P_NumIntD,
 @P_NumExtD,
 @P_TELLD,
 @P_TELLMovilD,
 @P_NombreT);
GO
----> MODIFICAR
CREATE PROCEDURE MODIFICAR_DIRECTOR (@P_ID_Director CHAR(10),
 @P_NomDirector VARCHAR(30),
 @P_PRIMER_APELLIDO VARCHAR(30),
 @P_SEGUNDO_APELLIDO VARCHAR(30),
 @P_EstadoD VARCHAR(30),
 @P_MunicipioD VARCHAR(30),
 @P_ColoniaD VARCHAR(30),
 @P_CalleD VARCHAR(30),
 @P_NumIntD VARCHAR(30),
 @P_NumExtD VARCHAR(30),
 @P_TELLD VARCHAR(30),
 @P_TELLMovilD VARCHAR(30),
 @P_NombreT VARCHAR(30)) AS 
 UPDATE DIRECTOR
 SET ID_Director=@P_ID_Director, 
NomDirector=@P_NomDirector, 
PRIMER_APELLIDO=@P_PRIMER_APELLIDO,
SEGUNDO_APELLIDO=@P_SEGUNDO_APELLIDO,
EstadoD=@P_EstadoD,
MunicipioD=@P_MunicipioD,
ColoniaD=@P_ColoniaD,
CalleD=@P_CalleD,
NumIntD=@P_NumIntD,
NumExtD=@P_NumExtD,
TELLD=@P_TELLD,
TELLMovilD=@P_TELLMovilD,
NombreT=@P_NombreT WHERE ID_Director=@P_ID_Director; 
GO
----> BORRAR
CREATE PROCEDURE BORRAR_DIRECTOR (@P_ID_Director CHAR(10)) AS 
IF EXISTS (SELECT *FROM DIRECTOR WHERE ID_Director=@P_ID_Director)
 BEGIN
 DELETE FROM DIRECTOR WHERE ID_Director=@P_ID_Director;
 END

EXECUTE AGREGAR_DIRECTOR 'D02','ERICK','VALENCIA','PASTRANA','CDMX','IZTACALCO','BENITO JUAREZ','CONSTITUCIÓN','200','356','5518923654','5516352482','NIKE';
EXECUTE MODIFICAR_DIRECTOR 'D02','ERIKA','VALENCIA','PASTRANA','CDMX','IZTACALCO','BENITO JUAREZ','CONSTITUCIÓN','200','356','5518923654','5516352482','Cuidadp con el michi';
EXECUTE BORRAR_DIRECTOR 'D02'; 
SELECT*FROM DIRECTOR;

------03
--->AGREGAR
CREATE PROCEDURE AGREGAR_AREA (@P_ID_AREA CHAR(10),
 @P_Nombre_Area VARCHAR(30),
 @P_TIENDA VARCHAR(30)) AS 
INSERT INTO AREA(ID_Area, 
Nombre_Area,
TIENDA)
VALUES (@P_ID_AREA, 
@P_Nombre_Area,
@P_TIENDA);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_AREA (@P_ID_AREA CHAR(10),
 @P_Nombre_Area VARCHAR(30),
 @P_TIENDA VARCHAR(30)) AS
 UPDATE AREA SET 
 ID_Area=@P_ID_AREA, 
 Nombre_Area=@P_Nombre_Area,
 TIENDA=@P_TIENDA WHERE ID_AREA=@P_ID_AREA;
GO
--->BORRAR
CREATE PROCEDURE BORRAR_AREA (@P_ID_AREA CHAR(10)) AS
 IF EXISTS (SELECT *FROM AREA WHERE ID_Area=@P_ID_AREA)
 BEGIN
 DELETE FROM AREA WHERE  ID_Area=@P_ID_AREA;
 END

EXECUTE AGREGAR_AREA 'G03','DAMA','NIKE';
EXECUTE MODIFICAR_AREA 'G02','NIÑO','Cuidadp con el michi';
EXECUTE BORRAR_AREA 'G03';
SELECT*FROM AREA;




------04
--->AGREGAR
CREATE PROCEDURE AGREGAR_EMPLEADO(@P_ID_Empleado CHAR(10),
 @P_ID_Area CHAR(10),
 @P_NomEmpleado VARCHAR(30),
 @P_PRIMER_APELLIDOE VARCHAR(30),
 @P_SEGUNDO_APELLIDOE VARCHAR(30),
 @P_EstadoE VARCHAR(30),
 @P_MunicipioE VARCHAR(30),
 @P_ColoniaE VARCHAR(30),
 @P_CalleE VARCHAR(30),
 @P_NumIntE VARCHAR(30),
 @P_NumExtE VARCHAR(30),
 @P_TELLE VARCHAR(30),
 @P_TELLMovilE VARCHAR(30),
 @P_TipoEmpleado VARCHAR(30)) AS 
INSERT INTO EMPLEADO(ID_Empleado,
ID_Area, 
NomEmpleado, 
PRIMER_APELLIDOE,
SEGUNDO_APELLIDOE,
EstadoE,
MunicipioE,
ColoniaE,
CalleE,
NumIntE,
NumExtE,
TELLE,
TELLMovilE,
TipoEmpleado)
VALUES (@P_ID_Empleado,
 @P_ID_Area,
 @P_NomEmpleado,
 @P_PRIMER_APELLIDOE,
 @P_SEGUNDO_APELLIDOE,
 @P_EstadoE,
 @P_MunicipioE,
 @P_ColoniaE,
 @P_CalleE,
 @P_NumIntE,
 @P_NumExtE,
 @P_TELLE,
 @P_TELLMovilE,
 @P_TipoEmpleado);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_EMPLEADO (@P_ID_Empleado CHAR(10),
 @P_ID_Area CHAR(10),
 @P_NomEmpleado VARCHAR(30),
 @P_PRIMER_APELLIDOE VARCHAR(30),
 @P_SEGUNDO_APELLIDOE VARCHAR(30),
 @P_EstadoE VARCHAR(30),
 @P_MunicipioE VARCHAR(30),
 @P_ColoniaE VARCHAR(30),
 @P_CalleE VARCHAR(30),
 @P_NumIntE VARCHAR(30),
 @P_NumExtE VARCHAR(30),
 @P_TELLE VARCHAR(30),
 @P_TELLMovilE VARCHAR(30),
 @P_TipoEmpleado VARCHAR(30)) AS
 UPDATE EMPLEADO
 SET ID_Empleado=@P_ID_Empleado,
ID_Area=@P_ID_Area, 
NomEmpleado=@P_NomEmpleado, 
PRIMER_APELLIDOE=@P_PRIMER_APELLIDOE,
SEGUNDO_APELLIDOE=@P_SEGUNDO_APELLIDOE,
EstadoE=@P_EstadoE,
MunicipioE=@P_MunicipioE,
ColoniaE=@P_ColoniaE,
CalleE=@P_CalleE,
NumIntE=@P_NumIntE,
NumExtE=@P_NumExtE,
TELLE=@P_TELLE,
TELLMovilE=@P_TELLMovilE,
TipoEmpleado=@P_TipoEmpleado WHERE ID_Empleado=@P_ID_Empleado; 
GO
--->BORRAR
CREATE PROCEDURE BORRAR_EMPLEADO (@P_ID_Empleado CHAR(10)) AS
IF EXISTS (SELECT *FROM EMPLEADO WHERE ID_Empleado=@P_ID_Empleado)
 BEGIN
 DELETE FROM EMPLEADO WHERE ID_Empleado=@P_ID_Empleado;
 END 

 DROP PROCEDURE BORRAR_EMPLEADO;
EXECUTE AGREGAR_EMPLEADO 'A21','G01','ERIKA','PASTRANA','ORDOÑEZ','CDMX','COYOACAN','MIGUEL HIDALGO','RAMITA','100','50','5517562654','55475632541','VENDEDOR';
EXECUTE MODIFICAR_EMPLEADO 'A20','G01','ERIKA','PASTRANA','ORDOÑEZ','CDMX','COYOACAN','MIGUEL HIDALGO','RAMITA','100','50','5517562654','55475632541','VIGILANTE';
EXECUTE BORRAR_EMPLEADO 'A21';
SELECT*FROM EMPLEADO;

-----05
--->AGREGAR
CREATE PROCEDURE AGREGAR_VENDEDOR (@P_ID_EMPLEADO CHAR(10),
@P_ID_Area CHAR(10)) AS
INSERT INTO VENDEDOR (ID_EMPLEADO,
ID_Area)
VALUES(@P_ID_EMPLEADO,@P_ID_Area);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_VENDEDOR (@P_ID_EMPLEADO CHAR(10),
@P_ID_Area CHAR(10)) AS 
 UPDATE VENDEDOR
 SET ID_EMPLEADO=@P_ID_EMPLEADO,
ID_Area=@P_ID_Area WHERE ID_EMPLEADO=@P_ID_EMPLEADO; 
GO
--->BORRAR
CREATE PROCEDURE BORRAR_VENDEDOR (@P_ID_EMPLEADO CHAR(10)) AS
IF EXISTS (SELECT *FROM VENDEDOR WHERE ID_Empleado=@P_ID_Empleado)
 BEGIN
 DELETE FROM VENDEDOR WHERE ID_Empleado=@P_ID_Empleado;
 END 

DROP PROCEDURE BORRAR_VENDEDOR;
EXECUTE AGREGAR_VENDEDOR 'A20','G01';
EXECUTE MODIFICAR_VENDEDOR 'A20','G02';
EXECUTE BORRAR_VENDEDOR 'A20';
SELECT*FROM VENDEDOR;


-----06
--->AGREGAR
CREATE PROCEDURE AGREGAR_CAJERO
(@P_ID_EMPLEADO CHAR(10)) AS
INSERT INTO CAJERO(ID_EMPLEADO)
VALUES(@P_ID_EMPLEADO);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_CAJERO (@P_ID_EMPLEADO CHAR(10)) AS 
 UPDATE CAJERO
 SET ID_EMPLEADO=@P_ID_EMPLEADO WHERE ID_EMPLEADO=@P_ID_EMPLEADO; 
GO 
--->BORRAR
CREATE PROCEDURE BORRAR_CAJERO (@P_ID_EMPLEADO CHAR(10)) AS
IF EXISTS (SELECT *FROM CAJERO WHERE ID_Empleado=@P_ID_Empleado)
 BEGIN
 DELETE FROM CAJERO WHERE ID_Empleado=@P_ID_Empleado;
 END 
 
EXECUTE AGREGAR_CAJERO 'A20';
EXECUTE MODIFICAR_CAJERO 'A20';
EXECUTE BORRAR_CAJERO 'A20';
SELECT*FROM CAJERO;


-------07
--->AGREGAR
CREATE PROCEDURE AGREGAR_GERENTE
(@P_ID_EMPLEADO CHAR(10)) AS
INSERT INTO GERENTE(ID_EMPLEADO)
VALUES(@P_ID_EMPLEADO);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_GERENTE (@P_ID_EMPLEADO CHAR(10)) AS 
 UPDATE GERENTE
 SET ID_EMPLEADO=@P_ID_EMPLEADO WHERE ID_EMPLEADO=@P_ID_EMPLEADO; 
GO 
--->BORRAR
CREATE PROCEDURE BORRAR_GERENTE (@P_ID_EMPLEADO CHAR(10)) AS
IF EXISTS (SELECT *FROM GERENTE WHERE ID_Empleado=@P_ID_Empleado)
 BEGIN
 DELETE FROM GERENTE WHERE ID_Empleado=@P_ID_Empleado;
 END 

EXECUTE AGREGAR_GERENTE'A20';
EXECUTE MODIFICAR_GERENTE 'A20';
EXECUTE BORRAR_GERENTE 'A20';
SELECT*FROM GERENTE;

---08
--->AGREGAR
CREATE PROCEDURE AGREGAR_VIGILANTE
(@P_ID_EMPLEADO CHAR(10), @P_TIENDA VARCHAR(30)) AS
INSERT INTO VIGILANTE (ID_EMPLEADO,TIENDA)
VALUES(@P_ID_EMPLEADO,@P_TIENDA);
GO

--->MODIFICAR (Las tiendas se modifican con nombres ya existentes)
CREATE PROCEDURE MODIFICAR_VIGILANTE (@P_ID_EMPLEADO CHAR(10), 
@P_TIENDA VARCHAR(30)) AS 
 UPDATE VIGILANTE
 SET ID_EMPLEADO=@P_ID_EMPLEADO,
 @P_TIENDA=@P_TIENDA WHERE ID_EMPLEADO=@P_ID_EMPLEADO; 
GO 
--->BORRAR
CREATE PROCEDURE BORRAR_VIGILANTE (@P_ID_EMPLEADO CHAR(10)) AS
IF EXISTS (SELECT *FROM VIGILANTE WHERE ID_Empleado=@P_ID_Empleado)
 BEGIN
 DELETE FROM VIGILANTE WHERE ID_Empleado=@P_ID_Empleado;
 END 

EXECUTE AGREGAR_VIGILANTE 'A20','NIKE';
EXECUTE MODIFICAR_VIGILANTE 'A20','Cuidadp con el michi';
EXECUTE BORRAR_VIGILANTE 'A20';
SELECT*FROM VIGILANTE;


-------09
--->AGREGAR
CREATE PROCEDURE AGREGAR_PROVEEDOR(@P_ID_PROVEEDOR CHAR(30),
 @P_NomProveedor VARCHAR(30)) AS 
INSERT INTO PROVEEDOR(ID_PROVEEDOR, 
NomProveedor)
VALUES (@P_ID_PROVEEDOR, 
@P_NomProveedor);
GO

--->MODIFICAR
CREATE PROCEDURE MODIFICAR_PROVEEDOR (@P_ID_PROVEEDOR CHAR(30),
 @P_NomProveedor VARCHAR(30)) AS
 UPDATE PROVEEDOR
 SET ID_PROVEEDOR=@P_ID_PROVEEDOR, 
NomProveedor=@P_NomProveedor WHERE ID_PROVEEDOR=@P_ID_PROVEEDOR; 
GO 

--->BORRAR
CREATE PROCEDURE BORRAR_PROVEEDOR (@P_ID_PROVEEDOR CHAR(30)) AS
IF EXISTS (SELECT *FROM PROVEEDOR WHERE ID_PROVEEDOR=@P_ID_PROVEEDOR)
 BEGIN
 DELETE FROM PROVEEDOR WHERE ID_PROVEEDOR=@P_ID_PROVEEDOR;
 END 

EXECUTE AGREGAR_PROVEEDOR 'P02','VOGUE' ;
EXECUTE MODIFICAR_PROVEEDOR 'P02','ADIDAS';
EXECUTE BORRAR_PROVEEDOR 'P02';
SELECT*FROM PROVEEDOR;

------10
--->AGREGAR
CREATE PROCEDURE AGREGAR_COMPRA(@P_ID_PRODUCTO CHAR(10),
@P_NUM_COMPRA INTEGER,
@P_ID_PROVEEDOR CHAR(30),
@P_FECHA_COMPRA DATE,
@P_NUM_PIEZAS INTEGER,
@P_COSTO_U FLOAT,
@P_ID_Empleado CHAR(10)) AS
INSERT INTO COMPRA(ID_PRODUCTO,
NUM_COMPRA,
ID_PROVEEDOR,
FECHA_COMPRA,
NUM_PIEZAS,
COSTO_U,
ID_Empleado)
VALUES(@P_ID_PRODUCTO,
@P_NUM_COMPRA,
@P_ID_PROVEEDOR,
@P_FECHA_COMPRA,
@P_NUM_PIEZAS,
@P_COSTO_U,
@P_ID_Empleado);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_COMPRA (@P_ID_PRODUCTO CHAR(10),
@P_NUM_COMPRA INTEGER,
@P_ID_PROVEEDOR CHAR(30),
@P_FECHA_COMPRA DATE,
@P_NUM_PIEZAS INTEGER,
@P_COSTO_U FLOAT,
@P_ID_Empleado CHAR(10)) AS
 UPDATE COMPRA
 SET ID_PRODUCTO=@P_ID_PRODUCTO,
NUM_COMPRA=@P_NUM_COMPRA,
ID_PROVEEDOR=@P_ID_PROVEEDOR,
FECHA_COMPRA=@P_FECHA_COMPRA,
NUM_PIEZAS=@P_NUM_PIEZAS,
COSTO_U=@P_COSTO_U,
ID_Empleado=@P_ID_Empleado WHERE ID_PRODUCTO=@P_ID_PRODUCTO; 
GO 
--->BORRAR
CREATE PROCEDURE BORRAR_COMPRA (@P_ID_PRODUCTO CHAR(10)) AS
IF EXISTS (SELECT *FROM COMPRA WHERE ID_PRODUCTO=@P_ID_PRODUCTO)
 BEGIN
 DELETE FROM COMPRA WHERE ID_PRODUCTO=@P_ID_PRODUCTO;
 END 

EXECUTE AGREGAR_COMPRA 'VOGUE002',2,'P01','04/06/2021',12,250,'GE01';
EXECUTE MODIFICAR_COMPRA 'VOGUE001',5,'P01','05/06/2021',12,250,'GE01';
EXECUTE BORRAR_COMPRA 'VOGUE002';
SELECT *FROM COMPRA;

------11
--->AGREGAR
CREATE PROCEDURE AGREGAR_PRENDA(@P_ID_PRENDA CHAR(10),
 @P_Area CHAR(10),
 @P_TALLA CHAR(5),
 @P_MARCA VARCHAR(30),
 @P_EXISTENCIAS INTEGER,
 @P_TIPO_PRENDA VARCHAR(30),
 @P_PRECIO INTEGER) AS 
INSERT INTO PRENDA(ID_PRENDA,
Area, 
TALLA,
MARCA,
EXITENCIAS,
TIPO_PRENDA,
PRECIO)
VALUES (@P_ID_PRENDA,
@P_Area, 
@P_TALLA,
@P_MARCA,
@P_EXISTENCIAS,
@P_TIPO_PRENDA,
@P_PRECIO);
GO
--->MODIFICAR
CREATE PROCEDURE MODIFICAR_PRENDA (@P_ID_PRENDA CHAR(10),
 @P_Area CHAR(10),
 @P_TALLA CHAR(5),
 @P_MARCA VARCHAR(30),
 @P_EXISTENCIAS INTEGER,
 @P_TIPO_PRENDA VARCHAR(30),
 @P_PRECIO INTEGER) AS 
 UPDATE PRENDA
 SET ID_PRENDA=@P_ID_PRENDA,
Area=@P_Area, 
TALLA=@P_TALLA,
MARCA=@P_MARCA,
EXITENCIAS=@P_EXISTENCIAS,
TIPO_PRENDA=@P_TIPO_PRENDA,
PRECIO=@P_PRECIO WHERE ID_PRENDA=@P_ID_PRENDA; 
GO 
--->BORRAR
CREATE PROCEDURE BORRAR_PRENDA (@P_ID_PRENDA CHAR(10)) AS
IF EXISTS (SELECT *FROM PRENDA WHERE ID_PRENDA=@P_ID_PRENDA)
 BEGIN
 DELETE FROM PRENDA WHERE ID_PRENDA=@P_ID_PRENDA;
 END

EXECUTE AGREGAR_PRENDA 'VOGUE001','G02',12,'VOGUE',12,'SUDADERA',250;
EXECUTE MODIFICAR_PRENDA 'VOGUE001','G02',15,'VOGUE',12,'PANTALON',250;
EXECUTE BORRAR_PRENDA 'VOGUE001';
SELECT*FROM PRENDA;

--->MOSTRAR
CREATE PROCEDURE MOSTRAR_PRENDA(@P_ID_PRENDA CHAR(10),
 @P_Area CHAR(10) OUTPUT,
 @P_TALLA CHAR(5) OUTPUT,
 @P_MARCA VARCHAR(30) OUTPUT,
 @P_EXISTENCIAS INTEGER OUTPUT,
 @P_TIPO_PRENDA VARCHAR(30) OUTPUT,
 @P_PRECIO INTEGER OUTPUT)
AS
BEGIN
SELECT @P_Area = Area FROM PRENDA WHERE ID_PRENDA = @P_ID_PRENDA;
SELECT @P_TALLA = TALLA FROM PRENDA WHERE ID_PRENDA = @P_ID_PRENDA;
SELECT @P_MARCA = MARCA FROM PRENDA WHERE ID_PRENDA = @P_ID_PRENDA;
SELECT @P_EXISTENCIAS = EXITENCIAS FROM PRENDA WHERE ID_PRENDA = @P_ID_PRENDA;
SELECT @P_TIPO_PRENDA = TIPO_PRENDA FROM PRENDA WHERE ID_PRENDA = @P_ID_PRENDA;
SELECT @P_PRECIO = PRECIO FROM PRENDA WHERE ID_PRENDA = @P_ID_PRENDA;
END


-----12
--->AGREGAR
CREATE PROCEDURE AGREGAR_VENTA(@P_NUM_VENTA INTEGER,
@P_FECHA_VENTA DATE,
@P_ID_CAJERO CHAR(10),
@P_ARTICULO CHAR(10)) AS
INSERT INTO VENTA(NUM_VENTA,
FECHA_VENTA,
ID_CAJERO,
ARTICULO) VALUES(@P_NUM_VENTA,
@P_FECHA_VENTA,
@P_ID_CAJERO,
@P_ARTICULO);
GO

--->MODIFICAR
CREATE PROCEDURE MODIFICAR_VENTA (@P_NUM_VENTA INTEGER,
@P_FECHA_VENTA DATE,
@P_ID_CAJERO CHAR(10),
@P_ARTICULO CHAR(10))  AS
 UPDATE VENTA
 SET NUM_VENTA=@P_NUM_VENTA,
FECHA_VENTA=@P_FECHA_VENTA,
ID_CAJERO=@P_ID_CAJERO,
ARTICULO=@P_ARTICULO WHERE NUM_VENTA=@P_NUM_VENTA; 
GO 

--->BORRAR
CREATE PROCEDURE BORRAR_VENTA (@P_NUM_VENTA INTEGER) AS
IF EXISTS (SELECT *FROM VENTA WHERE NUM_VENTA=@P_NUM_VENTA)
 BEGIN
 DELETE FROM VENTA WHERE NUM_VENTA=@P_NUM_VENTA;
 END 

EXECUTE AGREGAR_VENTA 2,'04/06/2021','C01','NIKE001';
EXECUTE MODIFICAR_VENTA 2,'05/06/2021','C01','NIKE001';
EXECUTE BORRAR_VENTA 2;
SELECT*FROM VENTA;
DROP PROCEDURE BORRAR_VENTA